name: Setup GDAL
description: Install GDAL system dependencies
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        sudo apt-get update
        sudo apt-get -y install gdal-bin libgdal-dev python3-gdal
        sudo apt-get -y autoremove
        sudo apt-get clean
