name: Build and Publish to TestPyPI
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.13"
          enable-cache: true

      - name: Remove solaris
        run: |
          sudo rm -rf docker

      - name: Build package
        run: uv build

      - name: Publish to TestPyPI
        env:
          UV_PUBLISH_USERNAME: __token__
          UV_PUBLISH_PASSWORD: ${{ secrets.TEST_API_TOKEN }}
        run: uv publish --publish-url https://test.pypi.org/legacy/
